version: '3.4'

services:
  python:
    build: ./ops-tools/images/python
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./ops-tools/images/db:/var/lib/postgresql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
