# Generated by Django 3.0.3 on 2020-03-01 13:31

from django.db import migrations, models
import document.validators


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=600, upload_to='media/files/%Y/%m/%d', validators=[document.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
    ]
