# Generated by Django 3.0.4 on 2020-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200301_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='is_parsed'),
        ),
    ]
