# Generated by Django 3.0.4 on 2020-03-09 18:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20200309_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='freq_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
