# Generated by Django 3.0.5 on 2020-04-26 11:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0007_pdfdocument_freq_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('perplexity_score', models.FloatField(verbose_name='perplexity_score')),
                ('sparsity_phi_score', models.FloatField(verbose_name='sparsity_phi_score')),
                ('sparsity_theta_score', models.FloatField(verbose_name='sparsity_theta_score')),
                ('topic_dictionary', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('pdf_docs', models.ManyToManyField(to='document.PdfDocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
