# Generated by Django 3.0.5 on 2020-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicmodel',
            name='decorr_tau',
            field=models.FloatField(default=0, verbose_name='decorr_tau'),
        ),
        migrations.AddField(
            model_name='thematicmodel',
            name='num_tokens',
            field=models.IntegerField(default=0, verbose_name='num_tokens'),
        ),
        migrations.AddField(
            model_name='thematicmodel',
            name='num_topics',
            field=models.IntegerField(default=0, verbose_name='num_topics'),
        ),
        migrations.AddField(
            model_name='thematicmodel',
            name='phi_tau',
            field=models.FloatField(default=0, verbose_name='phi_tau'),
        ),
        migrations.AddField(
            model_name='thematicmodel',
            name='theta_tau',
            field=models.FloatField(default=0, verbose_name='theta_tau'),
        ),
    ]
